baseurl: /gothenburg
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: gothenburg
github_org: maptime
maptime:
  chapter: MaptimeGBG
  twitter: MaptimeGBG
  #disqus: YOUR DISQUS USERNAME
